# Dockerfile.worker

FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info", "--pool=solo"]